#ifndef CHIMP_COMMON_H
#define CHIMP_COMMON_H

// Following files are generated by CMake.
// You **must** build this library using CMake.
#include "chimp/cmake/config.h"
#include "chimp/cmake/export.h"

namespace chimp {

class App;
class AppBuilder;
class Arg;
class ArgBuilder;

class Error;
class LogicError;
class ParsingError;

#ifdef CHIMP_BUILD_TESTING
namespace testing {

  class AppTest;
  class AppBuilderTest;
  class ArgTest;
  class ArgBuilderTest;

} // namespace testing
#endif // CHIMP_BUILD_TESTING

} // namespace chimp

#endif // CHIMP_COMMON_H
